### PR TITLE
Pr/7454

### PR DESCRIPTION
**Pull request by spalger**
Implementation of generic status service from https://github.com/elastic/kibana/pull/7459 into https://github.com/elastic/kibana/pull/7454

### CODE REVIEW

**Comment by bevacqua** [comment]
Great. This is what I was hoping for!

**Comment by ycombinator** [comment]
Will merge this once https://github.com/elastic/kibana/pull/7459 is merged.

**Comment by spalger** [comment]
Done

**Comment by ycombinator** [comment]
Thanks again @spalger. This is much better than the hacks I was coming up with.

**Pull request merged**
